// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADdrXruSZhrqg-ggT1mV3usutAjGaiCrk',
    appId: '1:121367250826:web:a09f039a58990ed44cea73',
    messagingSenderId: '121367250826',
    projectId: 'capital-heart-clinic-tes-dc631',
    authDomain: 'capital-heart-clinic-tes-dc631.firebaseapp.com',
    storageBucket: 'capital-heart-clinic-tes-dc631.firebasestorage.app',
    measurementId: 'G-1QTNRNF8BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_lYBEDxdLaOeDJ6lM6cJgTqc0UjYTKs0',
    appId: '1:121367250826:android:13797cb61883c7114cea73',
    messagingSenderId: '121367250826',
    projectId: 'capital-heart-clinic-tes-dc631',
    storageBucket: 'capital-heart-clinic-tes-dc631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwhbKMSXR79salTEW1R1jvIUNQdcwxOo4',
    appId: '1:121367250826:ios:28c755605bf09b094cea73',
    messagingSenderId: '121367250826',
    projectId: 'capital-heart-clinic-tes-dc631',
    storageBucket: 'capital-heart-clinic-tes-dc631.firebasestorage.app',
    iosBundleId: 'com.premiumsoftwaretech.capitalHeartClinicManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwhbKMSXR79salTEW1R1jvIUNQdcwxOo4',
    appId: '1:121367250826:ios:28c755605bf09b094cea73',
    messagingSenderId: '121367250826',
    projectId: 'capital-heart-clinic-tes-dc631',
    storageBucket: 'capital-heart-clinic-tes-dc631.firebasestorage.app',
    iosBundleId: 'com.premiumsoftwaretech.capitalHeartClinicManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADdrXruSZhrqg-ggT1mV3usutAjGaiCrk',
    appId: '1:121367250826:web:d4db16b330fda3534cea73',
    messagingSenderId: '121367250826',
    projectId: 'capital-heart-clinic-tes-dc631',
    authDomain: 'capital-heart-clinic-tes-dc631.firebaseapp.com',
    storageBucket: 'capital-heart-clinic-tes-dc631.firebasestorage.app',
    measurementId: 'G-MH12BDVN01',
  );
}
